--- #start of an ansible playbook
- name: Intro to ansible playbooks #Describes our play
  hosts: all # defines the host group in your inventory
  become: yes # the become keyword enables user priveledge escalation. Think: "become this user that is defined, 
              #  so I can have access to execute this palybook."
  tasks: #Tasks are what you want to get done with the playbook. they are defined in a list format under
         # the task label.
  - name: Start servers with permissions # Each task requires a name. In this example we are starting some servers
    command: server start webServer1     # that we have permissions on, so we can extract and copy some specific data.
    #Example of a start server command

  - name: Test if server connection is established
    wait_for: webServer1 #wait_for waits for a condition before continuing
    port: 22
    state: started
    delay: 0
    timeout: 1

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /srv/myfiles/foo.conf
      dest: /etc/foo.conf
      owner: foo
      group: foo
      mode: '0644'
  when: webServer1 == connected # a contitional to execute this copyying directory procedure when we are connected to webServer1
... #End of an ansible playbook
    ansible-playbook PlaybookDemp.yml #this command runs an ansible playbook
  
